Symspell
Lucs1590/Nkocr pull request #32
Opened 2020-10-03 02:41 UTC by AlvaroCavalcante

## Symspell Update!

- Added an optional parameter to call Symspell 
- When the parameter is True, Symspell is loaded to memory and the output is correct based on suggestions!

2020-11-04 23:31 UTC, Lucs1590 requested changes
Your code is very good, my friend, but the integration tests for load_dict_to_memory and get_word_suggestion were missing. Would it be possible to insert them?

2020-11-04 23:31 UTC, Lucs1590 commented on src/auxiliary.py
> +    if len(get_digits) == 0:
Is it correct `== 0` here?

2020-11-05 00:00 UTC, AlvaroCavalcante commented on src/auxiliary.py
> +    if len(get_digits) == 0:
Ok, I'll add the tests then.

2020-11-06 03:24 UTC, Lucs1590 requested changes

2020-11-06 03:24 UTC, Lucs1590 commented on src/ocr_table.py
> +            self.text = ' '.join(self.text)
@AlvaroCavalcante, please put this inside the `run_pipeline` function?
https://github.com/Lucs1590/Nkocr/blob/c59128d4415e6e2e100771316c9fc418d9837caf/src/ocr_table.py#L70

2021-03-19 03:08 UTC, Lucs1590 approved these changes

2021-03-19 03:31 UTC, merged